server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/ai_platform}
    username: ${DB_USER:ai}
    password: ${DB_PASS:ai}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

ai:
  arango:
    url: ${ARANGO_URL:http://arangodb:8529}
    user: ${ARANGO_USER:root}
    pass: ${ARANGO_PASS:rootpwd}
